service: cart-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  stage: dev
  environment:
        DATABASE_HOST: db-instance-task-8.cxtgnve4poci.eu-west-1.rds.amazonaws.com
        DATABASE_PORT: 5432
        DATABASE_USERNAME: postgres
        DATABASE_PASSWORD: masterPassword
        DATABASE_NAME: cartDB

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /